export const beneficiaryRegistryAbi = [
  { type: "error", name: "BukanVerifier", inputs: [] },
  { type: "error", name: "PenerimaSudahTerdaftar", inputs: [] },
  { type: "error", name: "PenerimaTidakDitemukan", inputs: [] },
  {
    type: "function",
    name: "isVerifier",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "usulkanPenerima",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idHash", type: "bytes32" },
      { name: "wallet", type: "address" },
      { name: "btype", type: "uint8" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "perbaruiStatus",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idHash", type: "bytes32" },
      { name: "status", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "beneficiaries",
    stateMutability: "view",
    inputs: [{ name: "idHash", type: "bytes32" }],
    outputs: [
      { name: "idHash", type: "bytes32" },
      { name: "wallet", type: "address" },
      { name: "btype", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "metadataURI", type: "string" },
      { name: "registeredAt", type: "uint256" },
      { name: "registeredBy", type: "address" },
    ],
  },
] as const;

export const disbursementPoolAbi = [
  { type: "error", name: "ProgramTidakAktif", inputs: [] },
  { type: "error", name: "BukanEligible", inputs: [] },
  { type: "error", name: "BelumWaktunya", inputs: [] },
  { type: "error", name: "SudahDiklaim", inputs: [] },
  { type: "error", name: "CapTerlampaui", inputs: [] },
  { type: "error", name: "MasihMasaSanggah", inputs: [] },
  { type: "error", name: "LewatBatasNominal", inputs: [] },
  { type: "error", name: "BelumDisetujui", inputs: [] },
  {
    type: "function",
    name: "cairkan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "programId", type: "bytes32" },
      { name: "idHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "ajukanSanggahan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "programId", type: "bytes32" },
      { name: "idHash", type: "bytes32" },
      { name: "alasanURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "programs",
    stateMutability: "view",
    inputs: [{ name: "programId", type: "bytes32" }],
    outputs: [
      { name: "dtype", type: "uint8" },
      { name: "amountPerBeneficiary", type: "uint256" },
      { name: "periodInterval", type: "uint256" },
      { name: "totalCap", type: "uint256" },
      { name: "totalDisbursed", type: "uint256" },
      { name: "maxPerTransaction", type: "uint256" },
      { name: "token", type: "address" },
      { name: "active", type: "bool" },
    ],
  },
] as const;
